---
- name: Deploy Go repo to EC2 instance
  hosts: ec2
  become: yes


  vars_files:
    - vault.yml

  tasks:
    - name: Update package list and install required packages
      ansible.builtin.yum:
        name: ['git', 'golang', 'postgresql', 'postgresql-server', 'postgresql-contrib']
        state: latest

    - name: Set GOPATH
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: 'export GOPATH=$HOME/go'
        create: yes
        state: present

    - name: Clone the Go repo
      ansible.builtin.git:
        repo: https://github.com/nickcoast/gocsv.git
        dest: /home/ubuntu/go/src/gocsv
        version: master

    - name: Build the Go application
      ansible.builtin.command:
        cmd: go build -o /home/ubuntu/go/bin/gocsv
        chdir: /home/ubuntu/go/src/gocsv

    - name: Initialize PostgreSQL database
      command: postgresql-setup initdb

    - name: Configure PostgreSQL to allow password authentication
      replace:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: '^host.*all.*all.*127\.0\.0\.1/32.*ident'
        replace: 'host all all 127.0.0.1/32 md5'
        backup: yes

    - name: Start and enable PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL user for the Go app
      become_user: postgres
      postgresql_user:
        name: gocsv_user
        password: "{{ postgres_password }}"
        role_attr_flags: CREATEDB

    - name: Create PostgreSQL database for the Go app
      become_user: postgres
      postgresql_db:
        name: gocsv_db
        owner: gocsv_user

    - name: Create systemd service file
      ansible.builtin.template:
        src: gocsv.service.j2
        dest: /etc/systemd/system/gocsv.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start the Go application service
      ansible.builtin.systemd:
        name: gocsv
        state: started
        enabled: yes
